---
pipeline:
  # The Task result from this Task will be
  # returned from the pipeline.
  final_result_from: ObservationWindow 
  # specifies the kind of post-actions that will
  # follow the pipeline executtion.
  pipline_type: trigger_wobble_observations 
  tasks:
    task_1:
      # A Task that calculates n! and checks
      # that the result is larger than min_fact_val
      task_name: Factorials
      task_type: FactorialsTask
      task_options:
        fact_n: 25
      filter_options:
        min_fact_val: 1.e+20
    task_2:
      # A Task that evaluates observation windows
      # under the given conditions in the options
      task_name: ObservationWindow
      task_type: ObservationWindowTask
      task_options:
        max_zenith_deg: 60
        search_range_hours: 48
        max_sun_altitude_deg: -18.0
        max_moon_altitude_deg: -0.5
        precision_minutes: 2
        min_delay_minutes: 0
        max_delay_minutes: 1440  # = 60 * 24
        min_duration_minutes: 10
      filter_options:
        # will select the longest observation window
        # that fulfills the delay/duration requirements.
        min_window_duration_hours: 0.1
        max_window_delay_hours: 50
        window_selection: longest
    task_3:
      # check that the parameter count_rate in
      # the alert itself is large enough.
      task_name: CountRate
      task_type: ParameterTask
      filter_options:
        parameter_name: count_rate
        parameter_requirement: 1.e+3
        parameter_comparison: greater
    task_4:
      # check that the system_stable
      # parameter in the alert itself is True.
      task_name: SystemStable
      task_type: ParameterTask
      filter_options:
        parameter_name: system_stable
        parameter_requirement: True
        parameter_comparison: equal